apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendertron-deployment
  labels:
    app: rendertron
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rendertron
  template:
    metadata:
      labels:
        app: rendertron
    spec:
      containers:
      - name: rendertron
        image: rendertron:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000